web-config:
  cors:
    allowed:
      origins: http://localhost:5173
      methods: GET, POST, PUT, DELETE, HEAD

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_management_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: root
    baseline-version: 0

application:
  security:
    jwt:
      secret-key: 72395ec44eb1f7aa2761d4281e1f74739fb5acae5a8d3edf4e1a59e7663ae718
      expiration: 86400000
      refresh-token:
        expiration: 604800000
